# Generated by Django 3.1.7 on 2021-02-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['name', 'travel_time'], 'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
    ]
